services:
  mysql:
    image: mysql:8.0
    container_name: ${MYSQL_CONTAINER_NAME}
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysqldata:/var/lib/mysql
      - ./docker/db/data/initdb:/docker-entrypoint-initdb.d

volumes:
  mysqldata:
